### ISSUE TITLE
Replace Oxford Dictionaries API with something free

### ISSUE THREAD

**Issue by johan456789** [johan456789/yaktoa#5]
As announced [here](https://developer.oxforddictionaries.com/new-plans-announcement), the new introductory API includes 1000 calls in total so this is no longer ideal.

Maybe try [Merriam-Webster Dictionary API](https://dictionaryapi.com/).

![image](https://user-images.githubusercontent.com/14802181/176556284-356c923c-71bf-4071-b476-296bc63b0f53.png)

Or maybe just rely entirely on https://pypi.org/project/eng-to-ipa/

**Comment by nikhilnarla** [comment]
Hi @johan456789 , In my opinion, it would be better to use the **eng-to-ipa** module over the Merriam-webster API because it has no limits and also doesn't need the user to create an account, get an API key and place it in the config file, etc. I'm no expert but it just seems more user-friendly from an end-user point of view :). Let me know your thoughts on this.

**Comment by johan456789** [comment]
Thanks for pitching in. I currently only check Oxford Dictionary [when the word is not found in eng_to_ipa](https://github.com/johan456789/yaktoa/blob/1a0bc2c0373200e9f4e77e875c1bdb371560cd7c/ipa.py#L34) to save time and reduce API usage. 

User friendliness is a very good point. I now lean toward making API an optional setting. If it's not set and the word is not found in eng_to_ipa, then just leave the IPA field blank.

**Comment by nikhilnarla** [comment]
yeah, that makes sense. Is it ok if I work on that change?

**Comment by johan456789** [comment]
Sure, go for it!

**Comment by nikhilnarla** [comment]
Hi, @johan456789 I created a PR. Could you please check and let me know if I need to change anything?

**Comment by johan456789** [comment]
Merged
